language: java
jdk:
- openjdk15
services:
- docker
deploy:
  provider: heroku
  api_key:
    secure: l3VAR3+rhgR4qTl0ZIZKx05MTG6zw8w2oHsKlqwHSxXVMyLFsNArA0Eulro91Laty21qvC5Wk+39hObNl3XLbLp0rUWDGnU6zNo8jQORfUDgoE8U0B2lmVuBNVafoemRItmvtVXu4UbF/5ICbHLSxaqX6Sdc5eJM9ZZDRfob+NrTiwQRl9Invpf4uEkatDfogP/pMBie/kACKrbj3+Er0bJoZK2xy0YM/YsQx6B41phocfaGoBo8m9HWvtC2rqQevleZdco6HIfGVgAukXBZ6DJSlF5/Fg1OP+4lEoModlMh1+TX9tA3QZFQw3l1NQqaJmfVDGVN4lPTQ8Ho58ONJk6klzhg4E/fovXbQtUNinCUMP3RThi2hr4mSxSHc+STcGHMbVFdrQSUDzL9KMEYfnufyYRBsIYMvWwp7LzWNsLDrJ3/4W06hEbNAFT3a9HTDiHZ8V8H8dlW6zzzw7lk4uJuUKe9HLSutW8KASIvSuoGnOItUMPRStsAxy5wGxnq2dj+YH4jPYqHQcQOw0XNHFBnwuAUn3jowr67MMEVucDIOStdlq3otlz5GxwMn8Jz50TuICAv3c/b48IzC2w530kdmWOSjNAqHFBk48dz9dFwH9tAUM5qQslvbqycItfWZWdv2m/yFR6rsLoJcWgbLfeCtrwciZXVZWWZB4qjt4c=
  app: theregistry-staging
